### ISSUE TITLE
Setup EscapeWSSEAuthenticationBundle and FOSUserBundle

### ISSUE THREAD

**Issue by Lausebengel** [djoos/EscapeWSSEAuthenticationBundle#35]
Hello,

I'm trying to setup EscapeWSSEAuthenticationBundle and FOSUserBundle to secure my api. Does someone know a good tutorial about this ?
I tried it with this info :
https://github.com/escapestudios/EscapeWSSEAuthenticationBundle/issues/31
but it is to much fragmented. I didn't get it to work ...

Thanks in advance.

**Comment by skonsoft** [comment]
Hi,

I got it working by doing these steps:

### 1) Make a custom Provider with code:

```
 protected function getSalt(UserInterface $user)
    {
        return null;
    }
```
No need to get the salt, because it was already used in FOS User saved password

### 2) In Client side we should implement the same algorithm used by Symfony to hash password which is:
**sha512** algorithm with **5000** iterations. Here we need to get The Salt to generate the password. So we need to expose User Salt over the API to be used by the client.
Here is the function to generate the hashed password in client side:
```
// Here we suppose that you have already the User SALT. for example exposed by a public rest service
function hashPassword($password, $salt)
{
    $salted = $password . '{' . $salt . '}';
    $digest = hash('sha512', $salted, true);

    for ($i = 1; $i < 5000; $i++) {
        $digest = hash('sha512', $digest . $salted, true);
    }

    return base64_encode($digest);
}
```
And this is the wsse_header generator:
```
function wsse_header($username, $hashedPassword)
{
    $nonce = hash_hmac('sha512', uniqid(null, true), uniqid(), true);
    $created = new DateTime('now', new DateTimezone('UTC'));
    $created = $created->format(DateTime::ISO8601);
    $digest = hash('sha512', $nonce . $created . $hashedPassword, true);

    return sprintf(
            'X-WSSE: UsernameToken Username="%s", PasswordDigest="%s", Nonce="%s", Created="%s"',
            $username, base64_encode($digest), base64_encode($nonce), $created
    );
}
```
Finally, to use it just call:
```
wsse_header('someLogin',
                 hashPassword('somePassword', 'someSalt'));
```
**Note**: This was a PHP client, for Android, you case take a look here: 
[Android Client Tutorial](http://obtao.com/blog/2013/09/how-to-use-wsse-in-android-app/)
### 3) In security.yml, put:

```
encoder: #digest algorithm
                    algorithm: sha512
                    encodeHashAsBase64: true
                    iterations: 1 #Here one iteration, because in wsse_header we make only 1 iteration
```

I hope this help you !
regards
Skander

**Comment by xub** [comment]
gooooooooooood  @skonsoft
